name: Example Github Workflow

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 2,15 * * 1-5'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Create MP3 Dir
        run: mkdir mp3

      - name: Export Variables
        run: |
          export INSTAPAPER_CONSUMER_KEY="${{ secrets.INSTAPAPER_CONSUMER_KEY }}"
          export INSTAPAPER_CONSUMER_SECRET="${{ secrets.INSTAPAPER_CONSUMER_SECRET }}"
          export INSTAPAPER_USER_PASSWORD="${{ secrets.INSTAPAPER_USER_PASSWORD }}"
          export INSTAPAPER_USER_NAME="${{ secrets.INSTAPAPER_USER_NAME }}"

      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          linking-type: static
          # As of version 3 of this action, builds are no longer downloaded from GitHub
          # except on Windows: https://github.com/GyanD/codexffmpeg/releases.
          github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}

      - name: Instapaper API
        run: deno run -A main.ts

      - name: Merge audio files and insert chapters
        run: bash insert-chapter_and_merge-audio.sh

      - name: Create known_hosts
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: SCP Transfer
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > scp_key.pem
          chmod 600 scp_key.pem
          scp -i scp_key.pem -r mp3/$(date +"%Y%m%d%H").mp3 "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}":/home/"${{ secrets.SSH_USER }}"
